name: CI
on:
  pull_request:
    branches:
      - master
jobs:
  release:
    permissions:
      contents: write
      issues: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - run: pnpm ci
      - run: pnpm test
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpx semantic-release
